{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 10, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "filters", "default": null, "conditions": [], "min_value": 16, "max_value": 128, "step": 16, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "l2", "default": 0.1, "conditions": [], "values": [0.1, 0.3, 0.5], "ordered": true}}], "values": {"num_layers": 9, "filters": 16, "l2": 0.1}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 232, in _build_and_fit_model\n    model = self._try_build(hp)\n            ^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 164, in _try_build\n    model = self._build_hypermodel(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 155, in _build_hypermodel\n    model = self.hypermodel.build(hp)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/tmp/ipykernel_5587/2050381670.py\", line 5, in build_model\n    model.add(Conv2D(\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/models/sequential.py\", line 122, in add\n    self._maybe_rebuild()\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/models/sequential.py\", line 141, in _maybe_rebuild\n    self.build(input_shape)\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/layers/layer.py\", line 226, in build_wrapper\n    original_build_method(*args, **kwargs)\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/models/sequential.py\", line 187, in build\n    x = layer(x)\n        ^^^^^^^^\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/codespace/.python/current/lib/python3.12/site-packages/keras/src/ops/operation_utils.py\", line 221, in compute_conv_output_shape\n    raise ValueError(\nValueError: Computed output size would be negative. Received `inputs shape=(None, 0, 0, 16)`, `kernel shape=(3, 3, 16, 16)`, `dilation_rate=[1 1]`.\n"}